name: ci

on:
  push:
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - name: Install Ubuntu toolchain
        run: |
          sudo apt-get update
          sudo apt-get install --yes ninja-build clang
      - run: npm ci
      - run: npm run ci

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm test
      - run: cmake --preset dev
      - run: cmake --build --preset dev
      - run: ctest --preset dev
